/*

    Written by : Bebo
    DATE : 7/2/2019
    AUTOSAR Version : 4.3.1
    DOC Name : AUTOSAR_SWS_OS.pdf
    Target : ARM TIVA_C TM4C123GH6PM

*/

#ifndef OS_HEADERS_OSINTERNAL_HEADERS_OS_EVENT_INTERNAL_H_
#define OS_HEADERS_OSINTERNAL_HEADERS_OS_EVENT_INTERNAL_H_



#endif /* OS_HEADERS_OSINTERNAL_HEADERS_OS_EVENT_INTERNAL_H_ */
